// --- Agent Inbox Processor ---
// Runs every hour in the heartbeat phase. Reads AEGIS's unread
// inbox messages, processes them by type, acks, and responds.
// Zero LLM cost -- all processing is D1 reads/writes + memory lookups.
// For context_request: pull relevant memory and post a reply.
// For task_proposal: create agenda item for operator approval.
// For alert: escalate to agenda.
// For status_update/message: ack and optionally record to memory.

import { type EdgeEnv } from '../dispatch.js';
import { searchMemoryByKeywords, recordMemory } from '../memory-adapter.js';
import { addAgendaItem } from '../memory/index.js';

interface InboxMessage {
  id: string;
  sender: string;
  recipient: string;
  channel: string;
  msg_type: string;
  subject: string;
  body: string;
  created_at: string;
}

async function ackMessage(db: D1Database, id: string): Promise<void> {
  await db.prepare("UPDATE agent_inbox SET acked_at = datetime('now') WHERE id = ?").bind(id).run();
}

async function postReply(db: D1Database, sender: string, recipient: string, channel: string, msgType: string, subject: string, body: string): Promise<void> {
  const id = crypto.randomUUID();
  await db.prepare(`
    INSERT INTO agent_inbox (id, sender, recipient, channel, msg_type, subject, body)
    VALUES (?, ?, ?, ?, ?, ?, ?)
  `).bind(id, sender, recipient, channel, msgType, subject, body).run();
}

async function handleContextRequest(msg: InboxMessage, env: EdgeEnv): Promise<void> {
  // Extract keywords from subject + body for memory search
  const searchTerms = `${msg.subject} ${msg.body}`.slice(0, 500);

  // Search semantic memory (requires Memory Worker binding)
  const memories = env.memoryBinding
    ? await searchMemoryByKeywords(env.memoryBinding, searchTerms, 15)
    : [];

  // Also check episodic memory for recent conversations on the topic
  const episodes = await env.db.prepare(`
    SELECT intent, classification, outcome, created_at
    FROM episodic_memory
    WHERE intent LIKE ? OR classification LIKE ?
    ORDER BY created_at DESC LIMIT 10
  `).bind(`%${msg.subject.split(' ')[0]}%`, `%${msg.subject.split(' ')[0]}%`).all();

  // Build response
  const memorySection = memories.length > 0
    ? memories.map(m => `- [${m.topic}] ${m.fact} (confidence: ${m.confidence})`).join('\n')
    : '(no relevant memories found)';

  const episodeSection = (episodes.results?.length ?? 0) > 0
    ? (episodes.results as Array<{ intent: string; classification: string; outcome: string; created_at: string }>)
        .map(e => `- [${e.created_at}] ${e.classification}: ${e.intent?.slice(0, 100)}`)
        .join('\n')
    : '(no recent episodes)';

  const response = `## Context: ${msg.subject}

### Semantic Memory (${memories.length} entries)
${memorySection}

### Recent Episodes (${episodes.results?.length ?? 0})
${episodeSection}

---
_Auto-generated by AEGIS inbox processor in response to context_request from ${msg.sender}_`;

  await postReply(env.db, 'aegis', msg.sender, msg.channel, 'message', `Re: ${msg.subject}`, response);
  await ackMessage(env.db, msg.id);
  console.log(`[inbox] Replied to context_request from ${msg.sender}: ${msg.subject}`);
}

async function handleTaskProposal(msg: InboxMessage, env: EdgeEnv): Promise<void> {
  // Create agenda item for operator approval
  await addAgendaItem(
    env.db,
    `[${msg.sender.toUpperCase()}] Task proposal: ${msg.subject}`,
    `From ${msg.sender} via agent inbox:\n\n${msg.body}`,
    'medium',
  );

  await postReply(env.db, 'aegis', msg.sender, msg.channel, 'message',
    `Re: ${msg.subject}`,
    `Task proposal received and added to operator agenda for review. Will update when the operator responds.`);

  await ackMessage(env.db, msg.id);
  console.log(`[inbox] Task proposal from ${msg.sender} -> agenda: ${msg.subject}`);
}

async function handleAlert(msg: InboxMessage, env: EdgeEnv): Promise<void> {
  // Alerts go directly to high-priority agenda
  await addAgendaItem(
    env.db,
    `[ALERT:${msg.sender.toUpperCase()}] ${msg.subject}`,
    `Agent alert from ${msg.sender}:\n\n${msg.body}`,
    'high',
  );

  await ackMessage(env.db, msg.id);
  console.log(`[inbox] Alert from ${msg.sender} escalated to agenda: ${msg.subject}`);
}

async function handleStatusUpdate(msg: InboxMessage, env: EdgeEnv): Promise<void> {
  // Record significant status updates to memory
  if (env.memoryBinding) {
    await recordMemory(env.memoryBinding, 'aegis', `[${msg.sender}] ${msg.subject}: ${msg.body.slice(0, 500)}`, 0.7, 'agent_inbox');
  }
  await ackMessage(env.db, msg.id);
  console.log(`[inbox] Status update from ${msg.sender} recorded: ${msg.subject}`);
}

async function handleMessage(msg: InboxMessage, env: EdgeEnv): Promise<void> {
  // Generic messages -- ack and log
  await ackMessage(env.db, msg.id);
  console.log(`[inbox] Message from ${msg.sender} acked: ${msg.subject}`);
}

export async function runInboxProcessor(env: EdgeEnv): Promise<void> {
  // Read unread messages for AEGIS
  const result = await env.db.prepare(`
    SELECT id, sender, recipient, channel, msg_type, subject, body, created_at
    FROM agent_inbox
    WHERE (recipient = 'aegis' OR recipient = 'all')
      AND acked_at IS NULL
    ORDER BY created_at ASC
    LIMIT 20
  `).all<InboxMessage>();

  const messages = result.results ?? [];
  if (messages.length === 0) return;

  console.log(`[inbox] Processing ${messages.length} unread message(s)`);

  for (const msg of messages) {
    // Don't process our own broadcasts
    if (msg.sender === 'aegis' && msg.recipient === 'all') {
      await ackMessage(env.db, msg.id);
      continue;
    }

    try {
      switch (msg.msg_type) {
        case 'context_request':
          await handleContextRequest(msg, env);
          break;
        case 'task_proposal':
          await handleTaskProposal(msg, env);
          break;
        case 'alert':
          await handleAlert(msg, env);
          break;
        case 'status_update':
          await handleStatusUpdate(msg, env);
          break;
        case 'message':
        default:
          await handleMessage(msg, env);
          break;
      }
    } catch (err) {
      console.error(`[inbox] Error processing message ${msg.id} from ${msg.sender}:`, err instanceof Error ? err.message : String(err));
      // Ack anyway to prevent infinite reprocessing
      await ackMessage(env.db, msg.id);
    }
  }
}
